name: Ruby
on:
  pull_request:
jobs:
  SetUp:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6
        ports:
          - 5432:5432
        env:
          POSTGRES_UESR: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: 2.7.x

    - name: Set up Node.js
      run: |
        apt-get update
        apt-get install -y nodejs yarn

    - name: Cache Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.OS }}-gems-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.OS }}-gems-cache-

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-
    - name: Yarn Install
      run: yarn install --frozen-lockfile

    - name: Bundle Install
      bundle install --path=vendor/bundle --jobs 4 --retry 3

    - name: Set DB
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
  rspec:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Run Test
      run: |
        bundle exec rspec
  rubocp:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Run Rubocop
      run: |
        bundle exec rubocop
